# -*- mode: bash -*-
alias ll='ls -lAG'
alias gs='git status'
alias gaa='git add -A'
alias gc='git commit'
alias gs='git status'
alias gp='git push'
alias vim='$(brew --prefix vim)/bin/vim'
alias vi='vim'
alias undo='git reset HEAD~1 --soft'
