# Make electron apps use wayland
1password.Exec.electron = true
code.Exec.electron = true
"io.itch.itch".Exec.electron = true
"org.signal.Signal".Exec.electron = true


# Hide terminal editors / shells
[nvim]
MimeType.remove = true
Categories.remove = true
NoDisplay = "true"
Hidden = "true"

[Helix]
MimeType.remove = true
Categories.remove = true
NoDisplay = "true"
Hidden = "true"

[fish]
NoDisplay = "true"

[kitty-open]
MimeType.remove = true
NoDisplay = "true"
Hidden = "true"


# I don't want to open files in Zed by default
["dev.zed.Zed"]
MimeType.remove = true
Categories.remove = true
