extensions = [
    "auto-move-windows@gnome-shell-extensions.gcampax.github.com",
    "burn-my-windows@schneegans.github.com",
    "caffeine@patapon.info",
    "foresight@pesader.dev",
    "light-style@gnome-shell-extensions.gcampax.github.com",
    "nightthemeswitcher@romainvigier.fr",
    { uuid = "gsconnect@andyholmes.github.io", install = false },
]
