extensions = [
    "EditorConfig.EditorConfig",
    "ms-python.python",
    "ms-python.black-formatter",
    "tamasfe.even-better-toml",
    "rust-lang.rust-analyzer",
    "nvarner.typst-lsp",
    "tomoki1207.pdf",
    "alefragnani.bookmarks",
]
