set -x CARGO_MOMMYS_LITTLE 'pet/baby/toy'
set -x CARGO_MOMMYS_PRONOUNS 'their'
set -x CARGO_MOMMYS_ROLES 'daddy'
set -x CARGO_MOMMYS_MOODS 'chill/ominous/thirsty/yikes'
set -x CARGO_MOMMYS_PARTS 'sugar/milk'
